### ISSUE TITLE
The "Season" and "Difficulty" taxonomies are duplicated in the admin menu and frontend

### ISSUE THREAD

**Issue by w33zy** [dasmaeh/recipepress-reloaded#32]
Today I began work on the updated templates PR and I pulled the master branch to create the new branch. I saw the "update database" and I ran it. After I noticed that the "Season" and "Difficulty" are duplicated in the admin area menu and on the frontend.

[Edit] I notice that L430 of ````\admin\class-rpr-admin-migration.php```` mentions these 2 taxanomies

**Comment by jckoester** [comment]
Base of this problem is that the way db updates have been run in 0.7.x did not work on multisite install. They just haven't been triggered (#30).
In master I've  tried to find a fix for this. Obviously this fix is also triggered on a already migrated site. I'll lokk into this  asap.

**Comment by jckoester** [comment]
Could you please check for the entries `rpr_version_updated` and `rpr_dbversion` in the `wp_options`table.

**Comment by w33zy** [comment]
On my test site ````rpr_dbversion```` is set to ````4```` and I do not have a ````rpr_version_updated```` key in the ````wp_options```` table. However, I do have a ````rpr_update_needed```` key with a value of ````1````

This problem may have to do with the fact that I swap between branches often, some branches are on v.0.8.3 and some are on v0.8.4.0

**Comment by jckoester** [comment]
`rpr_dbversion` should be set to 5 in all version 0.8.x. This looks like your database didn't get updated properly. This could happen easily in a dev environment where you update plugins by swapping files without reactivating them. This is fixed in current master, where database updates get triggered on `admin_init`.
 Saving options probably got you a mixed state in the db, so the attempt to update your db to version 5 screwed things up.
